direction: right
grid-rows: 2
grid-gap: 20


style.fill: "transparent"
classes: {
  empty: {
    label: " "
    width: 60
    height: 60
    style: {
      fill: transparent
    }
  }
  transparent: {
    width: 60
    height: 60
    style: {
      fill: transparent
    }
  }
  regular: {
    width: 60
    height: 60
  }
  spacer: {
    label: " "
    width: 20
    height: 60
    style: {
      fill: transparent
      stroke-width: 0
    }
  }
}

pointer: "*pa" {
  label.near: outside-left-center
  style.fill: transparent
  style.stroke-width: 0

  grid-rows: 1
  grid-gap: 20

  1.class: transparent
  2.class: transparent
  3.class: transparent

  1: "pa"
  2: "pa+1"
  3: "pa+2"
}

pointer2: "*pb" {
  label.near: outside-left-center
  style.fill: transparent
  style.stroke-width: 0

  grid-rows: 1
  grid-gap: 20

  1.class: transparent
  2.class: transparent
  3.class: transparent

  1: "pb-2"
  2: "pb-1"
  3: "pb"
}

array: "a[10]" {
  label.near: outside-left-center
  style.fill: transparent
  style.stroke-width: 0

  grid-rows: 1
  grid-gap: 0

  space.class: spacer
  1: "a[0]"
  2.class: empty
  3.class: empty
  4.class: empty
  5.class: empty
  6.class: empty
  7.class: empty
  8.class: empty
  9: "a[8]"
  10.class: empty

  1.class: regular
  9.class: regular
}

pointer.1 -> array.1
pointer.2 -> array.2
pointer.3 -> array.3


pointer2.1 -> array.7
pointer2.2 -> array.8
pointer2.3 -> array.9
